# Generated by Django 3.2.9 on 2021-12-25 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stack_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='ans_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='question',
            name='votes',
            field=models.IntegerField(default=0),
        ),
    ]
