# Generated by Django 3.2.9 on 2021-12-26 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stack_app', '0003_question_answers'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='votes',
            field=models.IntegerField(default=0),
        ),
    ]
