# Generated by Django 3.2.9 on 2022-01-10 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stack_app', '0006_auto_20220109_1918'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='question_slug',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=models.TextField(default='Bio not provided'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='email',
            field=models.EmailField(default='Email not provided', max_length=254),
        ),
        migrations.AlterField(
            model_name='profile',
            name='full_name',
            field=models.CharField(default='Full Name not provided', max_length=100),
        ),
        migrations.AlterField(
            model_name='profile',
            name='location',
            field=models.CharField(default='Location not provided', max_length=100),
        ),
    ]
