# Generated by Django 3.2.9 on 2022-01-18 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stack_app', '0009_alter_question_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='title',
            field=models.CharField(max_length=500, unique=True),
        ),
    ]
